repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-lock
        name: checking if beekeepy/poetry.lock is consistent with pyproject.toml
        args: [ "-C", "./beekeepy", "--no-update" ]
        language_version: python3.10
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-lock
        name: checking if helpy/poetry.lock is consistent with pyproject.toml
        args: [ "-C", "./helpy", "--no-update" ]
        language_version: python3.10
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.9'
    hooks:
      - id: ruff
        name: linting code with Ruff
        args: [ "--fix" ]
      - id: ruff-format
        name: format code using Ruff formatter
  - repo: local
    hooks:
    - id: mypy
      name: type check with mypy
      entry: mypy
      language: system
      types: [ python ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          - "--create"
          - "--python-folders"
          - "\
            tests, \
            helpy, \
            beekeepy,
            "
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      -  id: shellcheck
